name: Selenium WebDriver CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install Chrome
        run: |
         sudo apt-get update
         sudo apt-get install -y google-chrome-stable
      
      - name: Install Dependancies
        run: dotnet restore SeleniumBasicExercice.sln

      - name: Build solution
        run: dotnet build SeleniumBasicExercice.sln --no-restore

      - name: Run TestProject2 tests
        env:
          CHROMEWEBDRIVER: /usr/bin/google-chrome
        run: 
          echo "Running tests in TestProject2"
          dotnet test ./TestProject2/TestProject2.csproj --verbosity normall

      - name: Run TestProject3 tests
        env:
          CHROMEWEBDRIVER: /usr/bin/google-chrome
        run: 
          echo "Running tests in TestProject3"
          dotnet test ./TestProject3/TestProject3.csproj --verbosity normall